name: Boardwoman
favicon: null
layout_spectrum: 0.06650294293649495
typography_spectrum: 0.34161377139389515
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.3269607978872955
  lightness: 0.45394400553777814
  saturation: 0.821950193727389
  rhythmicContrast: 0.5310267943423241
purpose: []
